# The distance that players can hear in local chat
Distance: 100
# Should plugin override global chat too?
Global_Chat_Override: false
# Should plugin use LuckPerms prefixes in global messages?
LuckPerms_Prefixes: true
# Should plugin log to file all messages
Logging_Messages: true
# RP chat options (chat for short distance chatting between players)
RP_chat:
  # Prefix for RP chat information
  Prefix: "&l&7[&l&5Local&l&7]&5"
  # Permission to toggle local chat messages
  Permission_To_RP_chat: "localchat.rp"
  # Color for messages in local chat
  Message_Color: "&d"
  # Command that toggles local chat
  Label: "rp"


# Global chat options (is enabled)
# Command to use that chat is /global
Global_chat:
  # Color for messages in Global chat
  Message_Color: "&b"
  # Prefix for Global chat (if luckperms is disabled/is not installed
  Prefix: "&l&b[GLOBAL]&a"
  # Permission to toggle global chat messages
  Permission_To_Global_chat: "localchat.global"
  # Command that toggles global chat
  Label: "global"


# DO NOT CHANGE THESE SETTINGS!!!
Prefix: "&l&7[&l&bLocal &l&aChat Manager&l&7]"
Log_Lag_Over_Millis: 100
Debug: [ ]
Version: 1
